version: "3.1"
name: cadastro-login-profile

services:
  api:
    ports:
      - "5000:3001"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SALT_ROUNDS=10
        - CLIENT=mysql
        - HOST=data_base
        - PORT=3306
        - USER=user
        - PASSWORD=password
        - DATABASE=db
    networks:
      - network
    depends_on:
      - data_base

  data_base:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3333:3306"
    expose:
      - "3306"
    volumes:
      - my-sql-data_base:/var/lib/mysql
    networks:
      - network
    hostname: data_base
volumes:
  my-sql-data_base:
networks:
  network:
